elaptopcheck: use tabs for spacing

diff --git a/bodhi/elaptopcheck/usr/bin/elaptopcheck b/bodhi/elaptopcheck/usr/bin/elaptopcheck
--- a/bodhi/elaptopcheck/usr/bin/elaptopcheck
+++ b/bodhi/elaptopcheck/usr/bin/elaptopcheck
@@ -10,10 +10,10 @@ if [[ "$DESKTOP" == *"Enlightenment"* ]] || [[ "$DESKTOP" == *"Moksha"* ]]; then
 		cp "/usr/share/bodhi/desktop/bodhi-help.desktop" "$DSK"
 	fi
 	if hash acpi 2>/dev/null; then
-			battery=$(acpi)
+		battery=$(acpi)
 	else
-			echo "Error: please install acpi!"
-			exit 1
+		echo "Error: please install acpi!"
+		exit 1
 	fi
 
 	start_path="/home/$USER/.e/e/applications/startup/startupcommands"
@@ -33,13 +33,13 @@ if [[ "$DESKTOP" == *"Enlightenment"* ]] || [[ "$DESKTOP" == *"Moksha"* ]]; then
 		LAYOUT=$(grep XKBLAYOUT < "$keyboard" | sed 's/XKBLAYOUT=//g')
 		if [ "$LAYOUT" == "$us" ]; then
 			enlightenment_remote -module-unload xkbswitch
-	 fi
- fi
- if [ -f "$start_path" ]; then
-  if [[ -n "$E_RESTART" ]]; then
-   sed -i 's/elaptopcheck//g' "$start_path"
-  fi
- fi
+		fi
+	fi
+	if [ -f "$start_path" ]; then
+		if [[ -n "$E_RESTART" ]]; then
+			sed -i 's/elaptopcheck//g' "$start_path"
+		fi
+	fi
 else
 	echo "Error: For enlightenment usage only."
 fi
